name: Build React Webpage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cancel:
    name: Cancel
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        if: ${{ github.event_name == 'push' }}
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
  build:
    name: Build
    needs: cancel
    runs-on: ubuntu-latest
    env:
      REACT_APP_QUOTES_API_URL: ${{ secrets.REACT_APP_QUOTES_API_URL }}
      REACT_APP_GITHUB_API_URL: ${{ secrets.REACT_APP_GITHUB_API_URL }}
      REACT_APP_SOCIALIFY_URL : ${{ secrets.REACT_APP_SOCIALIFY_URL }}
      REACT_APP_SOCIALIFY_URL_PARAM : ${{ secrets.REACT_APP_SOCIALIFY_URL_PARAM }}
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 14.x
    
    - name: Install NPM packages
      run: npm install
    
    - name: Build Generation
      run: npm run build

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: production-files
        path: ./build
        if-no-files-found: error
  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: production-files
        path: ./build

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
